name: yaplist
description: Task management application.

publish_to: "none"

version: 2.0.5+13

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  flutter_slidable: ^4.0.1
  path_provider: ^2.1.1
  lottie: ^3.2.0
  quick_actions: ^1.0.6
  flutter_native_splash: ^2.3.6
  google_mobile_ads: ^6.0.0
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_black.png
  color_dark: "#000000"
  image_dark: assets/images/splash_white.png

  android_12:
    image: assets/images/splash_black.png
    color: "#ffffff"
    image_dark: assets/images/splash_white.png
    color_dark: "#000000"
    fullscreen: true
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/animations/

  fonts:
    - family: YapListIcon
      fonts:
        - asset: fonts/YapListIcon.ttf
